// This file was generated by RedwoodJS
import { Success } from './BehavioralQuestionCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindBehavioralQuestionById, FindBehavioralQuestionByIdVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './BehavioralQuestionCell'

type CellInputs = CellProps<SuccessType, FindBehavioralQuestionById, FindBehavioralQuestionByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
