// This file was generated by RedwoodJS
import FatalErrorPageType from '/Users/len/code/adhd-interviews/web/src/pages/FatalErrorPage/FatalErrorPage'
import NotFoundPageType from '/Users/len/code/adhd-interviews/web/src/pages/NotFoundPage/NotFoundPage'
import ResourcesPageType from '/Users/len/code/adhd-interviews/web/src/pages/ResourcesPage/ResourcesPage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const NotFoundPage: typeof NotFoundPageType
  const ResourcesPage: typeof ResourcesPageType
}
