// This file was generated by RedwoodJS
import FatalErrorPageType from '/Users/len/code/adhd-interviews/web/src/pages/FatalErrorPage/FatalErrorPage'
import ForgotPasswordPageType from '/Users/len/code/adhd-interviews/web/src/pages/ForgotPasswordPage/ForgotPasswordPage'
import HomePageType from '/Users/len/code/adhd-interviews/web/src/pages/HomePage/HomePage'
import LoginPageType from '/Users/len/code/adhd-interviews/web/src/pages/LoginPage/LoginPage'
import NotFoundPageType from '/Users/len/code/adhd-interviews/web/src/pages/NotFoundPage/NotFoundPage'
import ResetPasswordPageType from '/Users/len/code/adhd-interviews/web/src/pages/ResetPasswordPage/ResetPasswordPage'
import ResourcesPageType from '/Users/len/code/adhd-interviews/web/src/pages/ResourcesPage/ResourcesPage'
import SignupPageType from '/Users/len/code/adhd-interviews/web/src/pages/SignupPage/SignupPage'
import BehavioralQuestionBehavioralQuestionPageType from '/Users/len/code/adhd-interviews/web/src/pages/BehavioralQuestion/BehavioralQuestionPage/BehavioralQuestionPage'
import BehavioralQuestionBehavioralQuestionsPageType from '/Users/len/code/adhd-interviews/web/src/pages/BehavioralQuestion/BehavioralQuestionsPage/BehavioralQuestionsPage'
import BehavioralQuestionEditBehavioralQuestionPageType from '/Users/len/code/adhd-interviews/web/src/pages/BehavioralQuestion/EditBehavioralQuestionPage/EditBehavioralQuestionPage'
import BehavioralQuestionNewBehavioralQuestionPageType from '/Users/len/code/adhd-interviews/web/src/pages/BehavioralQuestion/NewBehavioralQuestionPage/NewBehavioralQuestionPage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const ForgotPasswordPage: typeof ForgotPasswordPageType
  const HomePage: typeof HomePageType
  const LoginPage: typeof LoginPageType
  const NotFoundPage: typeof NotFoundPageType
  const ResetPasswordPage: typeof ResetPasswordPageType
  const ResourcesPage: typeof ResourcesPageType
  const SignupPage: typeof SignupPageType
  const BehavioralQuestionBehavioralQuestionPage: typeof BehavioralQuestionBehavioralQuestionPageType
  const BehavioralQuestionBehavioralQuestionsPage: typeof BehavioralQuestionBehavioralQuestionsPageType
  const BehavioralQuestionEditBehavioralQuestionPage: typeof BehavioralQuestionEditBehavioralQuestionPageType
  const BehavioralQuestionNewBehavioralQuestionPage: typeof BehavioralQuestionNewBehavioralQuestionPageType
}
