// This file was generated by RedwoodJS
import { Success } from './BehavioralQuestionsCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindBehavioralQuestions, FindBehavioralQuestionsVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './BehavioralQuestionsCell'

type CellInputs = CellProps<SuccessType, FindBehavioralQuestions, FindBehavioralQuestionsVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
