// This file was generated by RedwoodJS
import { Success } from './EditBehavioralQuestionCell'
import type { CellProps } from '@redwoodjs/web'
import type { EditBehavioralQuestionById, EditBehavioralQuestionByIdVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './EditBehavioralQuestionCell'

type CellInputs = CellProps<SuccessType, EditBehavioralQuestionById, EditBehavioralQuestionByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
